services:
  mimotion:
    build: .
    ports:
      - "9091:8000"
    env_file:
      - .env
    environment:
      - DATA_DIR=/data
      - MIMOTION_PATH=/app/mimotion/main.py
    volumes:
      - ./data:/data
    restart: unless-stopped
